[WIP] fix: Issue 1874 - Colorize checksec output
pwndbg/pwndbg pull request #1923
Opened 2023-10-20 01:45 UTC by CristhianMotoche

2023-10-20 16:33 UTC, disconnect3d requested changes
Hi, we have `pwndbg.color.*` functions to color things - let's use them instead of reimplementing coloring :)

2023-10-27 01:13 UTC, CristhianMotoche commented
Thanks for the tip @disconnect3d Let me know if it looks a bit better now.

2023-10-29 21:01 UTC, disconnect3d commented on pwndbg/commands/checksec.py
> +    return NEW_LINE.join(list(map(color_line, output.split(NEW_LINE))))
```suggestion
    return "\n".join(map(color_line, output.split(NEW_LINE)))
```

2023-10-29 21:01 UTC, disconnect3d commented on pwndbg/commands/checksec.py
> +NEW_LINE = "\n"
```suggestion
```

2023-11-02 02:03 UTC, disconnect3d commented on pwndbg/commands/checksec.py
> +
```suggestion
```

2023-11-02 02:03 UTC, disconnect3d commented on pwndbg/commands/checksec.py
> +
```suggestion
```

2023-11-12 03:37 UTC, disconnect3d commented on pwndbg/commands/checksec.py
> +    return "\n".join(map(color_line, output.split(NEW_LINE)))
```suggestion
    return "\n".join(map(color_line, output.split("\n")))
```

2023-11-16 07:39 UTC, disconnect3d approved these changes

2023-11-16 07:40 UTC, disconnect3d commented
I'm going to merge this since this should just work. However, in the future we should just use checksec from pwntools since it is our dependency right now

2023-11-16 07:40 UTC, merged