feat : use --no-cache-dir flag to pip in dockerfiles to save space
pwndbg/pwndbg pull request #2033
Opened 2024-02-25 08:42 UTC by Rajpratik71

using the "--no-cache-dir" flag in pip install, make sure downloaded packages by pip don't cache on the system. This is a best practice that makes sure to fetch from a repo instead of using a local cached one. Further, in the case of Docker Containers, by restricting caching, we can reduce image size. In terms of stats, it depends upon the number of python packages multiplied by their respective size. e.g for heavy packages with a lot of dependencies it reduces a lot by don't cache pip packages.

Further, more detailed information can be found at

https://medium.com/sciforce/strategies-of-docker-images-optimization-2ca9cc5719b6

Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

2024-02-25 23:46 UTC, intrigus-lgtm commented
Instead of changing the files, can't we simply set `ENV PIP_NO_CACHE_DIR=1` in the Dockerfile(s)?

2024-02-26 00:15 UTC, disconnect3d commented
> Instead of changing the files, can't we simply set `ENV PIP_NO_CACHE_DIR=1` in the Dockerfile(s)?

+1, this sounds like a better solution (?)

2024-02-26 13:02 UTC, disconnect3d requested changes
Please change this to envvar in dockerfiles instead of flag to pip in setup.sh/setup-dev.sh

2024-02-27 21:21 UTC, disconnect3d commented
Ping @Rajpratik71

2024-02-29 16:06 UTC, Rajpratik71 commented
Sorry @intrigus-lgtm  @disconnect3d  for the late response.

Env variable and value related to "PIP_NO_CACHE_DIR" are bit confusing i.e. why I thought to keep flag-based, see the thread at https://github.com/pypa/pip/issues/2897

2024-02-29 16:58 UTC, intrigus-lgtm commented
This is no longer a problem.
I don't have time to find the relevant issue that fixes this, but it should be no problem with any recent pip/python version.

2024-03-04 00:12 UTC, disconnect3d commented
> Sorry @intrigus-lgtm @disconnect3d for the late response.
> 
> Env variable and value related to "PIP_NO_CACHE_DIR" are bit confusing i.e. why I thought to keep flag-based, see the thread at [pypa/pip#2897](https://github.com/pypa/pip/issues/2897)

We wanted it to be added to Dockerfiles, not to setup.sh itself :P

This still needs changes :<

2024-03-06 11:18 UTC, disconnect3d commented
Please either reopen this or send another PR with proper fix for this.

2024-03-06 11:18 UTC, closed without merging

2024-03-06 13:38 UTC, rajpratik71 commented
@disconnect3d  Sorry for the confusion and delayed response new PR is ta https://github.com/pwndbg/pwndbg/pull/2068