Improve normal bins corruption check
pwndbg/pwndbg pull request #2289
Opened 2024-07-06 02:04 UTC by k4lizen

Closes https://github.com/pwndbg/pwndbg/issues/1196 and Closes https://github.com/pwndbg/pwndbg/issues/2287.
This PR is based off of https://github.com/pwndbg/pwndbg/pull/1564.
+ Added a new heap parameter: `heap_corruption_check_limit` which states for how many chunks the corruption check is done
+ As opposed to the previous PR, every chunk has its fd/bk pointers checked instead of comparing the two lists. This results in more thorough checking when the forward and backward lists do not overlap fully.
+ `heap_corruption_check_limit` is allowed to have both a lower and a higher value than `heap-dereference-limit` which means the name "heap-dereference-limit" isn't really fitting anymore, but okay

Note:
`heap-dereference-limit` isn't really properly handled when its negative (pwndbg crashes) or zero, gdb defaults to this message when its set to zero:
```bash
pwndbg> set heap-dereference-limit 0
Set number of chunks to dereference in each bin to 'unlimited'.
``` 
but thats not actually what happens, as one chunk is printed. I set it so that `heap_corruption_check_limit` acts similarly i.e. no corruption check is done when it's set to zero. This has the unfortunate consequence that when `heap_corruption_check_limit` is set to zero, and the bin arena pointers are 0x0 (corrupted), the bin reads as "empty". I'd say this is moreso a logic error in the function that calls bin_at but whatever.

I generally tried to make it so that both parameters don't freak out when they have weird values.

2024-07-07 17:56 UTC, CptGibbon commented
Thanks for this PR, I'll review next week.

2024-07-15 00:28 UTC, CptGibbon commented
@k4lizen before I review this, do you have any tests ready to commit that could avoid this regressing?

2024-07-15 00:32 UTC, k4lizen commented
I dont

2024-07-15 17:40 UTC, CptGibbon requested changes
Thanks for this PR 🙏
It looks good, appears to be much more accurate detecting bin corruption.

Just needs a regression test ensuring that bins aren't labelled as corrupt when `heap-dereference-limit` is lower than the number of chunks in a bin.

2024-07-19 18:24 UTC, k4lizen commented
Done

2024-07-19 18:25 UTC, k4lizen commented
Btw the debian CI/CD is a bit suspect: https://github.com/pwndbg/pwndbg/actions/runs/10012491583/job/27678119432?pr=2289
`Error: Unexpected error: Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.`
Is that expected?

2024-07-22 16:13 UTC, CptGibbon approved these changes

2024-07-23 09:38 UTC, disconnect3d commented
> Btw the debian CI/CD is a bit suspect: https://github.com/pwndbg/pwndbg/actions/runs/10012491583/job/27678119432?pr=2289 `Error: Unexpected error: Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.` Is that expected? It seems to be slowing down the job quite a bit.

I believe not, pls open an issue for that

2024-07-23 09:40 UTC, merged