Fix issue when searching for strings
pwndbg/pwndbg pull request #242
Opened 2017-04-23 20:29 UTC by zachriggle

Fixes part on #232

2017-04-24 19:59 UTC, disconnect3d commented
Are you sure this is working?

```
pwndbg> set context-sections 
Set which context sections are displayed by default (also controls order) to ''
pwndbg> b main
Breakpoint 1 at 0x419fd0
pwndbg> r somestringargv
Starting program: /usr/bin/bash somestringargv

Breakpoint 1, 0x0000000000419fd0 in main ()
Breakpoint main
pwndbg> search
usage: search [-h] [-t {byte,short,word,dword,qword,pointer,string,bytes}] [-1] [-2] [-4] [-8] [-p] [-x] [-s] [-e] [-w] [--save] [--no-save] [-n] value [mapping]
search: error: the following arguments are required: value
pwndbg> search somestring
search() got an unexpected keyword argument 'mapping'
'search': Search memory for byte sequences, strings, pointers, and integer values
pwndbg> search "somestring"
search() got an unexpected keyword argument 'mapping'
'search': Search memory for byte sequences, strings, pointers, and integer values
pwndbg> search -t string "somestring"
search() got an unexpected keyword argument 'mapping'
'search': Search memory for byte sequences, strings, pointers, and integer values
pwndbg> search -t string somestring
search() got an unexpected keyword argument 'mapping'
'search': Search memory for byte sequences, strings, pointers, and integer values
pwndbg> search -t bytes somestring
search() got an unexpected keyword argument 'mapping'
'search': Search memory for byte sequences, strings, pointers, and integer values
pwndbg> search -t bytes "somestring"
search() got an unexpected keyword argument 'mapping'
'search': Search memory for byte sequences, strings, pointers, and integer values
pwndbg> version
Gdb: GNU gdb (GDB) 7.12
Python: 3.6.0 (default, Jan 16 2017, 12:12:55)  [GCC 6.3.1 20170109]
Pwndbg: 1.0.0 build: 79c0e842
```

2017-04-24 20:07 UTC, disconnect3d commented on pwndbg/search.py
>      if end and start:
Probably would be better to change below `maps = [...]` into `maps = (...)` or maybe moving the ifs into `for`.

However both changes are not really super needed. In worst case scenario we have ~400 items in the list (tried on `google-chrome`).

2017-05-16 12:58 UTC, disconnect3d requested changes

2017-05-16 12:58 UTC, disconnect3d commented on pwndbg/commands/search.py
> +        mappings = [m for m in mappings if mapping in m.objfile]
`mapping` and `mappings` seems confusing to me...

Also below there is `pwndbg.search.search` called with `mapping=mapping` keyword argument and you have changed that command to get `mappings` keyword argument (NOTE: additional `s`). This is the reason the code is failing atm.

2017-05-16 13:22 UTC, disconnect3d commented on pwndbg/commands/search.py
> +        mappings = [m for m in mappings if mapping in m.objfile]
It should be just `mappings=mappings` in 149 line.

2017-05-16 13:54 UTC, disconnect3d commented on pwndbg/commands/search.py
> +        print(M.red("Could not find mapping %r" % mapping))
`import pwndbg.color.memory as M`

2017-05-16 13:55 UTC, disconnect3d commented on pwndbg/commands/search.py
> +        print(M.red("Could not find mapping %r" % mapping))
Also if we want to show 'errors' in red, we should probably do that with all of them

2017-05-16 16:35 UTC, zachriggle commented on pwndbg/commands/search.py
> +        mappings = [m for m in mappings if mapping in m.objfile]
`mapping` is a string, e.g. `"libc.so"`.

`mappings` is a list of `pwndbg.memory.Page` objects which describe memory mappings and their regions.

2017-05-19 17:12 UTC, zachriggle commented
@disconnect3d can you approve the review so this can merge to `stable`?

2017-05-20 00:08 UTC, disconnect3d approved these changes

2017-05-20 00:09 UTC, disconnect3d commented
@zachriggle sure

2017-05-20 02:02 UTC, zachriggle commented
Huh.

2017-05-20 02:04 UTC, merged