Kallsyms - cleanup and comments
pwndbg/pwndbg pull request #2508
Opened 2024-11-09 22:52 UTC by jetchirag

Added a few comments, cleaned up some code and code to detect whether we are working with little endian or big endian.

2024-11-10 00:56 UTC, disconnect3d commented
@fidgetingbits can u review this?

2024-11-11 03:00 UTC, fidgetingbits requested changes
Looks good aside from the one thing. Thanks for clarifying a bunch of the code with comments. As I don't have any big-endian VMs setup atm I can't test those changes.

2024-11-11 03:00 UTC, fidgetingbits commented on pwndbg/gdblib/kernel/kallsyms.py
> +        if position_le != -1:
I'm not sure how long this self.kernel_ro_mem.find() call actually takes, but just thinking of how many slow remote debugging sessions I've been stuck in... I think you should change this to only scan for be sequences if le isn't found?

2024-11-13 10:24 UTC, jetchirag commented on pwndbg/gdblib/kernel/kallsyms.py
> +        if position_le != -1:
Makes sense. Fixed in new commit.

2024-11-13 12:46 UTC, fidgetingbits approved these changes

2024-11-13 12:47 UTC, fidgetingbits commented
Looks good. You'll want to fix the linting errors though.

2024-11-16 01:48 UTC, disconnect3d commented
Hm is this correct? the Ci is failing on qemu on a test for this...

2024-11-19 16:33 UTC, jetchirag commented
@disconnect3d Can we try re-running the action? action log keeps loading for me and I can't see any error

2024-11-20 00:37 UTC, disconnect3d commented
@jetchirag 
```
2024-11-15T16:07:21.3046337Z tests/system/test_gdblib_kernel.py:84: AssertionError
2024-11-15T16:07:21.3046621Z =========================== short test summary info ============================
2024-11-15T16:07:21.3047528Z FAILED tests/system/test_gdblib_kernel.py::test_gdblib_kernel_kallsyms - AssertionError: assert 1729935402067167475 == 18446603338369587728
2024-11-15T16:07:21.3047872Z  +  where 18446603338369587728 = <function address at 0x7f6e589724d0>('commit_creds')
2024-11-15T16:07:21.3048549Z  +    where <function address at 0x7f6e589724d0> = <module 'pwndbg.gdblib.symbol' from '/home/runner/work/pwndbg/pwndbg/pwndbg/gdblib/symbol.py'>.address
2024-11-15T16:07:21.3049520Z  +      where <module 'pwndbg.gdblib.symbol' from '/home/runner/work/pwndbg/pwndbg/pwndbg/gdblib/symbol.py'> = <module 'pwndbg.gdblib' from '/home/runner/work/pwndbg/pwndbg/pwndbg/gdblib/__init__.py'>.symbol
2024-11-15T16:07:21.3050035Z  +        where <module 'pwndbg.gdblib' from '/home/runner/work/pwndbg/pwndbg/pwndbg/gdblib/__init__.py'> = pwndbg.gdblib
2024-11-15T16:07:21.3050384Z ============================== 1 failed in 9.54s ===============================
2024-11-15T16:07:21.3050679Z --------------------------------------------------------------------------------
2024-11-15T16:07:21.3051037Z If you want to debug tests locally, run ./tests.sh with the --pdb flag
2024-11-15T16:07:21.3051254Z --------------------------------------------------------------------------------
2024-11-15T16:07:21.3051259Z
2024-11-15T16:07:21.3051372Z Tests completed in 112 seconds
2024-11-15T16:07:21.3051377Z
2024-11-15T16:07:21.3051465Z *********************************
2024-11-15T16:07:21.3051570Z ********* TESTS SUMMARY *********
2024-11-15T16:07:21.3051658Z *********************************
2024-11-15T16:07:21.3051765Z Tests passed or skipped: 13
2024-11-15T16:07:21.3051853Z Tests failed: 1
2024-11-15T16:07:21.3051857Z
2024-11-15T16:07:21.3051986Z Failing tests: test_gdblib_kernel_kallsyms```

2024-11-24 16:14 UTC, disconnect3d commented
Ping @jetchirag

2025-01-15 10:01 UTC, disconnect3d commented
@jetchirag ping. @fidgetingbits hmm is this still relevant? (I think we may have had incorporated this into the codebase already?)

2025-01-22 11:00 UTC, disconnect3d commented
Closing due to conflicts and inactivity. :(

2025-01-22 11:00 UTC, closed without merging

2025-01-23 14:06 UTC, jetchirag commented
@disconnect3d Sorryy, I will open a new PR as soon as I get the time to fix these conflicts :/