extend next_call to take optional symbol/target to break on
pwndbg/pwndbg pull request #290
Opened 2017-06-01 09:35 UTC by anthraxx

2017-06-01 10:00 UTC, anthraxx commented
Special thanks to @ysf

2017-06-26 08:24 UTC, zachriggle commented on pwndbg/next.py
> -def break_next_call(address=None):
Please add docs for `symbol_regex`

2017-06-26 08:25 UTC, zachriggle commented on pwndbg/next.py
> -def break_next_call(address=None):
In particular, it's useful to have a few examples of how this ought to work

2017-06-26 08:28 UTC, zachriggle requested changes

2017-06-26 08:28 UTC, zachriggle commented on pwndbg/next.py
> +        if ins.target_const and re.match('%s$' % symbol_regex, hex(ins.target)):
It seems that the `$` is a trade-off between matching too many things, and forcing the user to add `.*` to all of their matches.  I think that if we're adding `$` at the end, we should also add `^` to the beginning.

2017-06-26 08:29 UTC, anthraxx commented
Match vall always matches from the very beginning, there is no need for the ^

2017-06-26 10:17 UTC, zachriggle commented
Huh, I was definitely thinking of `search`.  Thanks!

2017-06-26 10:18 UTC, merged