update for ida_script.py to handle ida 7.0
pwndbg/pwndbg pull request #308
Opened 2017-07-13 02:38 UTC by aidielse

2017-07-14 14:31 UTC, disconnect3d commented
What about `idaapi.save_database`?

```
Python>help(idaapi.save_database)
Help on function save_database in module idaapi:

save_database(*args)
    save_database(outfile, delete_unpacked) -> bool```
IIt seems to me this might work in all versions as I guess it is the idapython api and not this old(?) idc.

2017-07-18 18:21 UTC, disconnect3d commented
@aidielse bump

2017-08-02 21:54 UTC, zachriggle commented
LGTM

2017-08-02 21:55 UTC, zachriggle requested changes

2017-08-02 21:55 UTC, zachriggle commented on ida_script.py
> +if idaapi.IDA_SDK_VERSION == 700:
Might be worth doing `>= 700`

2017-08-03 23:34 UTC, aidielse commented
Sorry I haven't responded, I've been pretty busy.
@disconnect3d that works in 7.0, updated.

2017-08-03 23:39 UTC, disconnect3d commented
@aidielse Are you sure? I mean, I asked because this method is present on IDA 6.x a well.

But it turns out it has two arguments:
```python
Traceback (most recent call last):
  File "C:\Program Files (x86)\IDA 6.8\python\idaapi.py", line 601, in IDAPython_ExecScript
    execfile(script, g)
  File "Z:/home/dc/installed/pwndbg/ida_script.py", line 25, in <module>
    idaapi.save_database(idc.GetIdbPath() + '.' + dt)
  File "C:\Program Files (x86)\IDA 6.8\python\idaapi.py", line 50712, in save_database
    return _idaapi.save_database(*args)
TypeError: save_database expected 2 arguments, got 1
```

2017-08-03 23:46 UTC, disconnect3d commented
I spoke with @aidielse on IRC and he confirmed the `idaapi.save_database` works in IDA 7.x.

Thanks!

2017-08-03 23:46 UTC, disconnect3d approved these changes

2017-08-03 23:47 UTC, merged