Add dereference-limit and heap-dereference-limit parameters
pwndbg/pwndbg pull request #367
Opened 2017-12-12 17:34 UTC by zachriggle

This allows setting the number of pointers dereferenced during 'telescope'
and in the register context.  Separately, the number of heap bins which
are dereferenced can be set.

Fixes #352

2017-12-12 20:59 UTC, disconnect3d commented
This doesn't work:
```
pwndbg> version
Gdb: GNU gdb (GDB) 8.0.1
Python: 3.6.3 (default, Oct 24 2017, 14:48:20)  [GCC 7.2.0]
Pwndbg: 1.0.0 build: af746d7
pwndbg> context
'context': Print out the current register, instruction, and stack context.

    Accepts subcommands 'reg', 'disasm', 'code', 'stack', 'backtrace', and 'args'.
Traceback (most recent call last):
  File "/home/dc/installed/pwndbg/pwndbg/commands/__init__.py", line 100, in __call__
    return self.function(*args, **kwargs)
  File "/home/dc/installed/pwndbg/pwndbg/commands/__init__.py", line 192, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/dc/installed/pwndbg/pwndbg/commands/context.py", line 64, in context
    result.extend(func())
  File "/home/dc/installed/pwndbg/pwndbg/commands/context.py", line 76, in context_regs
    return [pwndbg.ui.banner("registers")] + get_regs()
  File "/home/dc/installed/pwndbg/pwndbg/commands/context.py", line 120, in get_regs
    desc = pwndbg.chain.format(value)
  File "/home/dc/installed/pwndbg/pwndbg/chain.py", line 82, in format
    chain = get(value, limit, offset, hard_stop, hard_end)
  File "/home/dc/installed/pwndbg/pwndbg/chain.py", line 37, in get
    for i in range(limit):
TypeError: 'Parameter' object cannot be interpreted as an integer
```

2017-12-12 21:12 UTC, disconnect3d requested changes
We have to cast `limit` to `int` to fix it.

2017-12-12 21:13 UTC, disconnect3d commented
Btw might not be a scope of this issue but this is probably off by one:
```
pwndbg> set dereference-limit 1
Set max number of pointers to dereference in a chain to 1
pwndbg> telescope vararg
No symbol table is loaded.  Use the "file" command.
00:0000│ rsp  0x0
01:0008│      0x63f7de3b99
02:0010│      0x7fffffffd208
03:0018│ rsi  0x7fffffffd210
04:0020│      0x7fffffffd218
05:0028│      0x7fffffffd220
06:0030│      0x7fffffffd228
07:0038│      0x7fffffffd230
pwndbg> set dereference-limit 2
Set max number of pointers to dereference in a chain to 2
pwndbg> telescope vararg
No symbol table is loaded.  Use the "file" command.
00:0000│ rsp  0x7fffffffd1f0 ◂— ...
01:0008│      0x7fffffffd1f8 ◂— ...
02:0010│      0x7fffffffd200 ◂— ...
03:0018│ rsi  0x7fffffffd208 ◂— ...
04:0020│      0x7fffffffd210 ◂— ...
05:0028│      0x7fffffffd218 ◂— ...
06:0030│      0x7fffffffd220 ◂— ...
07:0038│      0x7fffffffd228 ◂— ...
pwndbg> set dereference-limit 3
Set max number of pointers to dereference in a chain to 3
pwndbg> telescope vararg
No symbol table is loaded.  Use the "file" command.
00:0000│ rsp  0x7fffffffd1f0 ◂— 0x0
01:0008│      0x7fffffffd1f8 ◂— 0x63f7de3b99
02:0010│      0x7fffffffd200 —▸ 0x7fffffffd208 ◂— ...
03:0018│ rsi  0x7fffffffd208 —▸ 0x7fffffffd210 ◂— ...
04:0020│      0x7fffffffd210 —▸ 0x7fffffffd218 ◂— ...
05:0028│      0x7fffffffd218 —▸ 0x7fffffffd220 ◂— ...
06:0030│      0x7fffffffd220 —▸ 0x7fffffffd228 ◂— ...
07:0038│      0x7fffffffd228 —▸ 0x7fffffffd230 ◂— ...
```

2017-12-15 19:21 UTC, zachriggle commented
Yeah, I think we need to change all of the `range()` statements to include `+1`

2017-12-16 15:56 UTC, disconnect3d commented
@zachriggle we still miss casting parameters to int (and so this code doesnt work)

2017-12-21 23:17 UTC, disconnect3d approved these changes
lgtm

2017-12-21 23:17 UTC, merged