Add  to ArgparsedCommand; move some commmands to Argparsed~
pwndbg/pwndbg pull request #373
Opened 2017-12-16 18:32 UTC by disconnect3d

2017-12-16 18:33 UTC, disconnect3d commented
Continuation of https://github.com/pwndbg/pwndbg/issues/244

2017-12-21 20:17 UTC, zachriggle requested changes
I'm pretty sure this breaks the docstrings on these functions.

2017-12-21 20:17 UTC, zachriggle commented on pwndbg/commands/__init__.py
> +        assert parser is None or desc is None, 'Invalid ArgparsedCommand usage'
I'd prefer a tiny bit of magic where we take a single argument and just check `isinstance(...)`

2017-12-22 23:38 UTC, disconnect3d commented
@zachriggle This do not break docstrings as they are set by `_ArgparsedCommand`:
```python
class _ArgparsedCommand(Command):
    def __init__(self, parser, function, *a, **kw):
        self.parser = parser
        self.parser.prog = function.__name__
        self.__doc__ = function.__doc__ = self.parser.description
        super(_ArgparsedCommand, self).__init__(function, *a, **kw)
```

```
In : pwndbg.commands.canary.canary.__doc__
'Print out the current stack canary.'
```

---
I have also changed it to use `parser_or_desc` argument with `isinstance` as you suggested.

I have also found out that `canary` has been broken by some previous changes. I am going to address that in another PR.

2017-12-22 23:38 UTC, merged

2017-12-23 01:58 UTC, zachriggle commented
Thanks! 😘
On Fri, Dec 22, 2017 at 5:38 PM Disconnect3d <notifications@github.com>
wrote:

> Merged #373 <https://github.com/pwndbg/pwndbg/pull/373>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pwndbg/pwndbg/pull/373#event-1400223864>, or mute the
> thread
> <https://github.com/notifications/unsubscribe-auth/AAG0GK7rLHyd07VEAH-CQJKFWSxH3WIxks5tDD2JgaJpZM4REauF>
> .
>

2017-12-23 01:58 UTC, zachriggle commented
Wrong emoji. ❤️
On Fri, Dec 22, 2017 at 7:57 PM Zach Riggle <zachriggle@gmail.com> wrote:

> Thanks! 😘
> On Fri, Dec 22, 2017 at 5:38 PM Disconnect3d <notifications@github.com>
> wrote:
>
>> Merged #373 <https://github.com/pwndbg/pwndbg/pull/373>.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/pwndbg/pwndbg/pull/373#event-1400223864>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe-auth/AAG0GK7rLHyd07VEAH-CQJKFWSxH3WIxks5tDD2JgaJpZM4REauF>
>> .
>>
>