Add filepath banner to source code debugging
pwndbg/pwndbg pull request #522
Opened 2018-09-12 00:32 UTC by disconnect3d

As in https://github.com/pwndbg/pwndbg/issues/521

2018-09-12 00:42 UTC, disconnect3d commented
@anthraxx @zachriggle can u guys review this? :)

2018-09-12 15:09 UTC, anthraxx requested changes

2018-09-12 15:09 UTC, anthraxx commented on pwndbg/info.py
> +    end = start + l[start+1:].index('"') + 1
we should use `rindex` here as the filename can contain quotes itself (plus then we dont even need [start+1:])

2018-09-12 15:09 UTC, anthraxx commented on pwndbg/ui.py
> +        size_to_trunc = len(title) - (width - len('-[  ]-'))
you can't use `'-[  ]-'` it can be overriden by `config.banner_title_surrounding_left` and `config.banner_title_surrounding_right` like below

2018-09-12 16:43 UTC, anthraxx approved these changes

2018-09-12 18:26 UTC, zachriggle commented
I don't mind adding the filename / path, but the changes to `banner` seem odd.  I don't generally like using `banner()` for the filename anyway.

Can we prepend the filename to the source listing instead?

2018-09-12 23:07 UTC, disconnect3d commented
> Can we prepend the filename to the source listing instead?

Like this?:
```
----[ SOURCE (CODE) ]----
File: some_path.c
1. // the source code
2. #include <whatever>
3.
4. ...
```

I am not very much for the banner changes either, so this solution is fine for me.
@anthraxx What do u think?

2018-09-16 19:13 UTC, disconnect3d commented
Closing this; see https://github.com/pwndbg/pwndbg/pull/526

2018-09-16 19:13 UTC, closed without merging