Fix inaccuracies in vis_heap_chunks()
pwndbg/pwndbg pull request #708
Opened 2020-02-18 13:20 UTC by CptGibbon

The `vis_heap_chunks` command incorrectly determines the boundaries between chunks near to a top chunk. For example, in the image below there are 3 identical, allocated chunks of minimum size which `vis_heap_chunks` wrongly shows as having different shapes. The 2nd invocation has not printed the trailing quadword of the 1st chunk, despite it being correctly marked as belonging to the chunk in the 1st output.

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/16000770/74738894-b1606500-524f-11ea-89c6-248df8d73f11.png">

This PR corrects the boundary calculation of chunks adjacent to a top chunk, it also uses a list of boundary addresses to do so, rather than a dictionary of every quadword in each printed chunk. The image below shows `vis_heap_chunks` output after the patch has been applied, each chunk looks identical and the 2nd invocation prints the last quadword of the 1st chunk.

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/16000770/74739303-7579cf80-5250-11ea-8a6e-e8f27a208573.png">

The colours change between screenshots because the original implementation subtracted 1 from a `color_func_idx` variable that was already 0 before building the output buffer.

2020-02-29 01:14 UTC, disconnect3d commented
@GrosQuildu or @stnevans any chance one of u could review this?

2020-03-12 09:40 UTC, GrosQuildu commented
`heap_region = main_heap.get_heap_boundaries(address)`

2020-03-12 16:05 UTC, GrosQuildu requested changes

2020-03-12 16:05 UTC, GrosQuildu commented on pwndbg/commands/heap.py
> +        prev_inuse = size_field & pwndbg.constants.ptmalloc.PREV_INUSE
```suggestion
        prev_inuse = main_heap.chunk_flags(size_field)[0]
```

2020-03-12 16:05 UTC, GrosQuildu commented on pwndbg/commands/heap.py
>      ptr_size = pwndbg.arch.ptrsize
Just for quality, not really important.
```suggestion
    ptr_size = main_heap.size_sz
```

2020-03-12 16:05 UTC, GrosQuildu commented on pwndbg/commands/heap.py
> +        if (cursor == top_chunk and not naive) or (cursor == heap_region.end - 0x10):
0x10 - magic constant, maybe better will be:
```suggestion
        if (cursor == top_chunk and not naive) or (cursor == heap_region.end - ptr_size*2):
```

2020-03-12 16:05 UTC, GrosQuildu commented on pwndbg/commands/heap.py
> +        color_func = color_funcs[color_func_idx]
```suggestion
        color_func = color_funcs[c % len(color_funcs)]
```

2020-03-12 16:05 UTC, GrosQuildu commented on pwndbg/commands/heap.py
> +            cell_hex = '\t0x{:0{n}x}'.format(cell, n=ptr_size*2)
Does pwndbg have some uniform way to print stuff like that? That is: address, memory, content, and labels, kinda like hexdump. @disconnect3d 

Probably not?

2020-03-17 11:43 UTC, disconnect3d commented on pwndbg/commands/heap.py
> +            cell_hex = '\t0x{:0{n}x}'.format(cell, n=ptr_size*2)
I think not

2020-03-17 11:44 UTC, disconnect3d commented
@CptGibbon ping :)

2020-03-17 17:07 UTC, CptGibbon commented
> @CptGibbon ping :)

I'm on it 👍

2020-03-17 21:41 UTC, CptGibbon commented
> Can we make it works with non-heap regions? Running `vis_heap_chunks` on arbitrary address may be useful when you are constructing fake chunks on i.e. stack. Currently its not possible because [`main_heap.get_heap_boundaries(address)`](https://github.com/pwndbg/pwndbg/blob/7f963fed0e8f54de93101a33ce30e66d497fb058/pwndbg/commands/heap.py#L508) crashes.

Sure, I've addressed this in 62f1180.

2020-03-18 09:44 UTC, GrosQuildu commented
Seems ok, thanks.

@disconnect3d can merge that one.

2020-03-18 09:45 UTC, GrosQuildu approved these changes
OK

2020-03-18 11:39 UTC, merged