fix prev chunk size check
pwndbg/pwndbg pull request #837
Opened 2020-10-07 02:16 UTC by lonnywang

**before fix :**
![image](https://user-images.githubusercontent.com/20320324/95279675-e4f70a80-0885-11eb-92af-499b6fde4ebb.png)

**after fix :**
![image](https://user-images.githubusercontent.com/20320324/95279755-0fe15e80-0886-11eb-9571-5aaf2227b4ba.png)

2020-10-14 16:17 UTC, disconnect3d commented
@GrosQuildu can you check that one?

2020-10-14 16:17 UTC, disconnect3d commented
@lonnywong can you give some more context? it's hard to judge if the  change is correct from the screenshots :P

2020-10-14 23:04 UTC, lonnywong commented
> @lonnywong can you give some more context? it's hard to judge if the change is correct from the screenshots :P

```c
#include <stdio.h>
#include <stdlib.h>

int main() {
	void *p1 = malloc(0x500);
	void *p2 = malloc(0x500);
	free(p1);
	printf("pwndbg> try_free %p\n", p2);
	getchar();
	return 0;
}
```

2020-10-15 09:51 UTC, GrosQuildu requested changes
Cool, thanks. We may simplify it and merge.

2020-10-15 09:51 UTC, GrosQuildu commented on pwndbg/commands/heap.py
> +            if chunksize(unsigned_size(prev_chunk['size'])) != prev_size:
```suggestion
            if prev_chunk_size != prev_size:
```

2020-10-15 09:51 UTC, GrosQuildu commented on pwndbg/commands/heap.py
>                  err = err.format(prev_size, prev_chunk_addr, unsigned_size(prev_chunk['size']))
```suggestion
                err = err.format(prev_size, prev_chunk_addr, prev_chunk_size)
```

2020-10-15 11:22 UTC, lonnywong commented on pwndbg/commands/heap.py
> +            if chunksize(unsigned_size(prev_chunk['size'])) != prev_size:
Good point.

2020-10-15 11:22 UTC, lonnywong commented on pwndbg/commands/heap.py
>                  err = err.format(prev_size, prev_chunk_addr, unsigned_size(prev_chunk['size']))
Good point.

2020-10-15 11:47 UTC, GrosQuildu approved these changes

2020-10-15 11:48 UTC, merged

2020-10-16 09:37 UTC, disconnect3d commented
Thanks!